### ISSUE TITLE
Door issues on Pubby Station, an attempt to help deal with improper doors. (Top Half of the station)

### ISSUE THREAD

**Issue by Nidvex250** [Sea-of-Lost-Souls/Tannhauser-Gate#336]
I was told to report on the github for any doors that were missed when the new door code was implemented into Pubby, so here we are! Attached are pictures pointing at the problem doors and remote door controllers, a couple lockers also have a problem and I've also pointed out a couple strangely placed items. First time I've done a post like this so hopefully I'm doing this correctly!
![dorms janitor](https://user-images.githubusercontent.com/66303093/182079816-7ca452bb-070a-4674-88ba-aaf5a90fe18d.png)
![Dorms Comissary](https://user-images.githubusercontent.com/66303093/182073416-c2e4cfa1-2e89-4e90-a294-ed7c30e58f37.png)
![Cargo Shuttle Access](https://user-images.githubusercontent.com/66303093/182073882-846472f9-57c8-4705-b0cf-3c77f29c7ab3.png)
![Cargo Security](https://user-images.githubusercontent.com/66303093/182074098-dbe88700-6bf7-4159-ae76-1cef9eae0165.png)
![Hallway area near HoP](https://user-images.githubusercontent.com/66303093/182074584-bef35808-1e1c-49b4-bfa5-c7d3846e5931.png)
![Bridge](https://user-images.githubusercontent.com/66303093/182075255-b684ceb7-cdbd-492c-9544-06f65e996645.png)
At this point we can safely assume that all the remote door control buttons don't work.
![Custodial and Customs](https://user-images.githubusercontent.com/66303093/182075706-705d9567-3604-42e6-8756-0c13b5f6fc81.png)
![Aux Base Construction](https://user-images.githubusercontent.com/66303093/182075895-92b71b34-1dee-40c6-97a5-4992c11a6c5d.png)
![Primary Tool Storage Shutter buttons](https://user-images.githubusercontent.com/66303093/182076034-9ecbffdb-1d13-46cc-8643-7cbcb864006c.png)
![Security, east side](https://user-images.githubusercontent.com/66303093/182077136-4fb5f107-b9e1-496c-a5d7-ca2dd13d2ca1.png)
![equipment room](https://user-images.githubusercontent.com/66303093/182077150-ca211b06-65b9-4d78-822b-d2dfb8dbb5f4.png)
![the labor shuttle](https://user-images.githubusercontent.com/66303093/182077809-e3d6bd7d-ce50-4eb5-82be-c4347bb00fb8.png)
![Detective Hallway](https://user-images.githubusercontent.com/66303093/182078811-c4739a8e-76a6-4176-8bb0-39bdbb3397f7.png)

This is more or less the top half of the station, I probably missed a few things in Sec (didn't check Perma yet) but I need to call it a night, hopefully this helps!

**Comment by ChakatStormCloud** [comment]
More for the pile:

### All of these only require maint access top open, and should require more.

<details>
<summary>Medical</summary>
CMO office maint

![image](https://i.imgur.com/99T4AOL.png)

Chemistry maint

![image](https://user-images.githubusercontent.com/16537322/182489864-c3968b18-200b-45c0-98a1-fee02968caf6.png)

psychology maint

![image](https://user-images.githubusercontent.com/16537322/182491019-579d4150-ffce-426c-87ca-cbec816c2051.png)

Medical Maint

![image](https://user-images.githubusercontent.com/16537322/182490837-4e0dfd8c-2569-40d6-89e2-54a3364e0071.png)

Morgue

![image](https://user-images.githubusercontent.com/16537322/182491282-14e98cd9-c047-4e4f-83d8-6c4a8618a9db.png)

</details>

<details>
<summary>Engineering</summary>
Tech Storage

![image](https://user-images.githubusercontent.com/16537322/182490335-c2bdd7a6-4da3-4c33-9ea2-05e4e9418eb5.png)

Engineering maint

![image](https://user-images.githubusercontent.com/16537322/182490519-3aad0bfe-5115-4ca7-a1bd-327ba3fab20e.png)

Atmos

![image](https://i.imgur.com/Bkjwcy1.png)

</details>
<details>
<summary>Service</summary>
Bar backroom

![image](https://user-images.githubusercontent.com/16537322/182480612-4df0594c-5a28-412d-8310-221d5802cc79.png)

Bar

![image](https://user-images.githubusercontent.com/16537322/182480694-f3e403f7-baa5-4d36-ad50-be40f5c87da2.png)

Botany

![image](https://user-images.githubusercontent.com/16537322/182480836-8f9e11dc-2038-4880-b104-c0e8f1a9665d.png)

Theater

![image](https://user-images.githubusercontent.com/16537322/182485184-b83bb738-6f3b-405b-a2ef-8f4ebfb18bd6.png)

Kitchen Coldroom

![image](https://user-images.githubusercontent.com/16537322/182494842-c8f1dceb-e74c-4a5d-bcc0-96e9af486a21.png)

</details>
<details>
<summary>Cargo</summary>
QM office

![image](https://user-images.githubusercontent.com/16537322/182494198-f75324cc-ffc4-4f7d-b564-77059d3af92a.png)

Cargo north maint.

![image](https://user-images.githubusercontent.com/16537322/182485027-943794c9-652f-4c40-9f79-cb8455ab708a.png)

this one too

![image](https://user-images.githubusercontent.com/16537322/182494397-b75307f2-5209-4b22-95ba-c212cfacb286.png)

Cargo south maint

![image](https://user-images.githubusercontent.com/16537322/182493716-c009f2c9-8ed6-4c30-9784-afe5cc235092.png)

Mining

![image](https://user-images.githubusercontent.com/16537322/182493776-dcc7fd10-b711-4660-bb41-8b5d58e5942e.png)

</details>
<details>
<summary>Science</summary>
Science maint North

![image](https://user-images.githubusercontent.com/16537322/182493878-019bc7ea-9586-490d-9588-8a2185b4c8e4.png)

Genetics (Monkey theft!)

![image](https://user-images.githubusercontent.com/16537322/182494060-787438fb-b1cf-4767-a6e4-f01b9f89c3b7.png)

RnD

![image](https://user-images.githubusercontent.com/16537322/182483694-013304b7-bfd5-4ed6-a1ad-90c7b0bfea88.png)

</details>
<details>
<summary>Security</summary>
Detective Office

![image](https://user-images.githubusercontent.com/16537322/182494994-9c1ed65d-bf65-4246-8b69-b052f07ae506.png)

Law Office

![image](https://user-images.githubusercontent.com/16537322/182495033-b0679b2d-3015-4915-92bf-d17f1462ca12.png)

Security Crematorium

![image](https://user-images.githubusercontent.com/16537322/182495084-ab62c15a-ac1a-4590-a454-0afb0a3b8be7.png)

Brig Infirmary

![image](https://user-images.githubusercontent.com/16537322/182495135-ff899380-9928-4206-9fef-c7bebe753ac0.png)

</details>
<details>
<summary>Other</summary>
NE Solar

![image](https://user-images.githubusercontent.com/16537322/182482723-31d04604-c41c-4210-bb90-aed4a6cefd3c.png)

NW Solar

![image](https://user-images.githubusercontent.com/16537322/182481034-45663d95-9039-403c-a0a8-3ed1f8518a67.png)

</details>

### Wall-doors!
<details>
<summary>The glory of a door, with the conveinence of a WALL! </summary>
All of these are also openable with only maint access, though only the atmos connection is likely an issue on that front

Cargo maint, north

![image](https://user-images.githubusercontent.com/16537322/182484648-3d15c6fd-c597-4a14-b695-cdc810e20251.png)

Another walldoor, this time reinforced

![image](https://user-images.githubusercontent.com/16537322/182487881-b0257d62-8860-4465-a13c-eccc89743dad.png)

Brig Atmos connection

![image](https://user-images.githubusercontent.com/16537322/182495476-9f80e25d-8cfc-4532-96e0-e73b5f7f186f.png)

</details>

### Maint doors that require MORE than maint
<details>
Between Med and sec

![image](https://user-images.githubusercontent.com/16537322/182495994-5c6937a0-b2f9-4221-85ce-a1a2785eb70b.png)

Science hallway

![image](https://user-images.githubusercontent.com/16537322/182496053-48731d65-e21c-4689-8d7b-02ffb7321cdb.png)

</details>

**Comment by Kittayecat** [comment]
the doors that lead to departments shouldnt have maint access at all, and instead, simply just departmental access, as per other maps, otherwise you will have problems of medical not being able to enter medical maint, the wall door is seemingly just a stray "abandoned" airlock helper, though theres a few more issues when it comes to pubby, like trash making certain parts of maints inaccessible

**Comment by ORCACommander** [comment]
the hack.io document was saying to use the dept's maint helper for their maint doors and to use the any version instead of the all version :/

**Comment by ORCACommander** [comment]
and why is the abandonned airlock helper sealing passages?

**Comment by Kittayecat** [comment]
its basically a random effect for the airlocks, they can be bolted, welded, cut wires, or simply have a wall inside them, as for the maints dept door helper, it shouldnt be giving assistants access? unless i had made a mistake with my test IDs, which is completely possible

**Comment by Kittayecat** [comment]
or its intentional, and im just making a general error on my own part
