### ISSUE TITLE
Pubby Access reports part 2

### ISSUE THREAD

**Issue by Kittayecat** [Sea-of-Lost-Souls/Tannhauser-Gate#338]
Atmos door in medmaint has incorrect codes
![image](https://user-images.githubusercontent.com/29833986/182245244-76fe8f78-e929-48bb-ae52-46b582508bc8.png)

Airlocks towards Chapel has incorrect codes
![image](https://user-images.githubusercontent.com/29833986/182245554-eef6f8c3-6404-4d35-a7ae-781eaef9f4ab.png)

Door towards the chaplains office has incorrect codes
![image](https://user-images.githubusercontent.com/29833986/182245929-089ac879-49b8-48f3-8c17-c4a4cdf289b3.png)

External access to the chaplains office has incorrect codes
![image](https://user-images.githubusercontent.com/29833986/182246104-84b83749-d8c4-4671-85e8-99a126933c5a.png)

CE office lacks access to lockdown and storage buttons on the left wall only
![image](https://user-images.githubusercontent.com/29833986/182246701-5125763f-db1d-49a0-956a-2afc93634e62.png)

Eng secure storage button lacks access (should be CE only i think? this button is technically a duplicate but it IS convenient)
![image](https://user-images.githubusercontent.com/29833986/182246892-afd697ab-d0d8-4232-80e7-9c59316a5aac.png)

Cargo Maints doors have wrong access
![image](https://user-images.githubusercontent.com/29833986/182250709-2d44329e-5145-4021-b81d-85d94488ab51.png)

Emitter shutter buttons have wrong access (though realistically the whole SM room needs to be redesigned)
![image](https://user-images.githubusercontent.com/29833986/182247197-4e196700-8e39-425e-9b56-ca5ce0260f79.png)

HFR lockdown shutters have wrong access 
![image](https://user-images.githubusercontent.com/29833986/182247431-b71c9ae9-1a6d-47e1-8000-7b6b7465f16f.png)

Medical maints doors have wrong access
![image](https://user-images.githubusercontent.com/29833986/182247800-2fd0549b-5516-401a-834a-2005a785524e.png)
![image](https://user-images.githubusercontent.com/29833986/182247911-b9c66ccd-fdd9-4fd0-b630-54b749641d05.png)

Medical Doors, Lockdown, and chemistry quick access buttons have wrong access
![image](https://user-images.githubusercontent.com/29833986/182248839-700c6996-fd83-4a7d-8a4b-05f6be167784.png)

Viro access buttons have wrong access
![image](https://user-images.githubusercontent.com/29833986/182249257-3b198681-eb0f-479d-a9cd-887298fda3f0.png)

Service buttons have wrong access
![image](https://user-images.githubusercontent.com/29833986/182249690-2c800eee-075e-407f-b016-a0aca510e31d.png)
![image](https://user-images.githubusercontent.com/29833986/182249769-a5eb76e9-3982-421e-8a7d-d534843af8ae.png)
![image](https://user-images.githubusercontent.com/29833986/182249855-dbedd35a-c935-4b4e-ab67-29ea64fa0048.png)
![image](https://user-images.githubusercontent.com/29833986/182250044-3182118a-d197-419c-9d79-ce00c5a2e847.png)

Robotics Charging shutter button, and lockdown button have wrong access
![image](https://user-images.githubusercontent.com/29833986/182250232-ab84c103-0bd1-415c-b1bb-3f5278337136.png)

and lastly, most maint doors to departments, that should be dept access instead of maint, are accessable by maints, allowing unintended things like assistants being able to waltz right into the CMO office, or Chemistry, all maints doors going to departments, should require access to that dept only, so botanists can go into maints around service, etc, the exception to this is doors cross through a department to traverse to another section of maints like this

![image](https://user-images.githubusercontent.com/29833986/182250635-6700c6b9-9684-4454-9fb5-4b9322db878c.png)

which should be "one access" for both cargo and maints

**Comment by ORCACommander** [comment]
image 1: that is an atmos dept door. requires either atmos access or engineering main access. also has an abandonned helper
image 2: requires any engineering external access

Last note: Doors are using dept maints codes. we have the low pop configs enabled that expands id card access when round start population is below threshold
