### ISSUE TITLE
Pubby: Missing Feature: Arc Mining

### ISSUE THREAD

**Issue by Nidvex250** [Sea-of-Lost-Souls/Tannhauser-Gate#518]
Mining recently got a new feature called Arc Mining, which generates boulders as Miners find and secure Nodes on lavaland that can be teleported up to the station and processed by a factory belt on station. While Miners can acquire enough mining points to buy a set from their mining vender, every current map has a production line at round-start. These machines are listed as "bouldertech" according to the var editor.
![Arc Mining](https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/assets/66303093/2ca49bd6-7e4d-4797-adae-0ff869c834c7)

**Comment by Mortisduem** [comment]
I am not seeing an example of this on the existing map yet. I am trying to find the needed machines in the files.

As for where to put I am thinking we shift the cyurrent miners office ~3-6 tiles west adjusting the docking port and some of the cargo maint in that area like the cargo drone workshop maint connection.
