### ISSUE TITLE
Pubby: Map Fixing: Supermatter Engine Room and Atmos.

### ISSUE THREAD

**Issue by Nidvex250** [Sea-of-Lost-Souls/Tannhauser-Gate#524]
This one is merely a mapping issue we've seen for a while now; the Temperature control units for the SM and Atmos' Air Distribution Loop are facing the wrong way and are not connected to the pipes as they should be. Also, the Delam Counter is clipping into the SM Chamber's Airlock.
![Mapping issues](https://github.com/Sea-of-Lost-Souls/Tannhauser-Gate/assets/66303093/4fdd576e-3720-4086-8696-f76a75f097c3)

**Comment by Mortisduem** [comment]
Corrected, adding to next map Pull
